import type { Metadata } from "next";
import { Inter } from "next/font/google";

// Set the font with Next.js
const inter = Inter({ subsets: ["latin"] });

// Export the metadata separately
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// This is a server component and does not include "use client"
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
